.TH MEDIAN 1 MEDIAN
.SH NAME
median - Calculate the median values for a set of groups
.SH SYNOPSIS
.B median
<
.I INPUT
.SH DESCRIPTION
.B median
takes the first blank space-separated column values and the remainder
as keys. It will then print the median for each key. As a side effect
median will print the result sorted by the keys.
.SH EXAMPLES
.nf
$ cat <<EOF | median
\-10
2
4
3
50
EOF
3
.fi
.PP
.nf
$ cat <<EOF | median
\+003  c
\&.001  a
\-002  b
\+001  c
\-001  b
\+002  c
EOF
\&.001  a
\-001.5  b
\+002  c
.fi
.SH RATIONALE
Combining
.BR sort (1),
.BR sed (1),
.BR wc (1),
.BR expr (1)
to do this is too much work to do on a regular basis.
.SH "SEE ALSO"
.BR sort (1),
.BR expr (1),
.BR sets (1)
.PP
Full documentation available locally via: info \(aq(median)\(aq
.SH AUTHORS
Principal author, Mattias Andrée.  See the COPYING file for the full
list of authors.
.SH LICENSE
Copyright \(co 2014, 2015  Mattias Andrée
.br
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
.SH BUGS
Please report bugs to https://github.com/maandree/median/issues or to
maandree@member.fsf.org
